# Generated by Django 4.0.1 on 2022-02-19 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_rename_addresslist_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_quantity', models.IntegerField()),
                ('product_image1', models.ImageField(upload_to='products')),
                ('product_image2', models.ImageField(upload_to='products')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='products')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=20)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('not packed', 'not packed'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='not packed', max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
