# Generated by Django 4.0.1 on 2022-02-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
