# Generated by Django 4.0.4 on 2022-06-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderhistory_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='payment',
        ),
    ]
