# Generated by Django 4.0.1 on 2022-02-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='product',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='category',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
    ]
