# Generated by Django 4.0.1 on 2022-02-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_categoryoffer_product_categoryoffer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
