# Generated by Django 4.0.1 on 2022-03-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_mrp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mrp_id',
            new_name='mrp',
        ),
    ]
